version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gfb_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gfb_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount migrations to run on init
      - ./apps/backend/passport-service/migrations/init.sql:/docker-entrypoint-initdb.d/001_passport.sql
      - ./apps/backend/iot-service/migrations/002_create_telemetry.sql:/docker-entrypoint-initdb.d/002_iot.sql
    networks:
      - gfb_net

  passport-service:
    build:
      context: ./apps/backend/passport-service
      dockerfile: Dockerfile
    container_name: gfb_passport_service
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/gfb_db?sslmode=disable
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - gfb_net

  iot-service:
    build:
      context: ./apps/backend/iot-service
      dockerfile: Dockerfile
    container_name: gfb_iot_service
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/gfb_db?sslmode=disable
      - PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - gfb_net

  blockchain-service:
    build:
      context: ./apps/backend/blockchain-service
      dockerfile: Dockerfile
    container_name: gfb_blockchain_service
    environment:
      - PORT=3000
      - RPC_URL=https://rpc-amoy.polygon.technology
      - PRIVATE_KEY=11d9aa36e00148c062a2511f63071bfb50f57d5df9c5abf64fdb67a9c1779e89
      - CONTRACT_ADDRESS=0x34991cE9703C683e83C639A60632192fCa82728e
    ports:
      - "3000:3000"
    networks:
      - gfb_net

  frontend-portal:
    build:
      context: ./apps/frontend/portal
      dockerfile: Dockerfile
    container_name: gfb_frontend
    environment:
      - PORT=3001
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3005:3001"
    links:
      - passport-service
      - iot-service
      - blockchain-service
    networks:
      - gfb_net

networks:
  gfb_net:
    driver: bridge

volumes:
  postgres_data:
